[functions.create-pdf]
    included_files = ["netlify/functions/bin/*"]

[[plugins]]
    package = './plugins/copy-chromium-binaries'

[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"

[dev]
    command= "pnpm dev || ( npm install pnpm && pnpm dev )"
    targetPort= 3000
    port = 8080
