[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[functions.create-pdf]
    included_files = ["netlify/functions/bin/*"]

[[plugins]]
    package = './plugins/copy-chromium-binaries'

[dev]
    command= "pnpm dev"
    targetPort= 3000
    port = 8080
